package notepad;

import java.awt.Color;
import javax.swing.JOptionPane;

public class CreateAccountFrame extends javax.swing.JFrame {

    public CreateAccountFrame() {
        initComponents();
        createProgressBar.setVisible(false);
        creatingAccountLabel.setVisible(false);
        new ProgressBarColor();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createUserField = new javax.swing.JTextField();
        createPasswordField = new javax.swing.JPasswordField();
        createCreateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        createProgressBar = new javax.swing.JProgressBar();
        creatingAccountLabel = new javax.swing.JLabel();
        createAccountBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(280, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createUserField.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        createUserField.setForeground(new java.awt.Color(255, 255, 255));
        createUserField.setBorder(null);
        getContentPane().add(createUserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 140, 33));
        createUserField.setOpaque(false);
        createUserField.setBackground(new Color(0,0,0,0));

        createPasswordField.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        createPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        createPasswordField.setBorder(null);
        getContentPane().add(createPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, 32));
        createPasswordField.setOpaque(false);
        createPasswordField.setBackground(new Color(0,0,0,0));

        createCreateButton.setText("Create");
        createCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCreateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, 30));

        backButton.setText("Cancel");
        backButton.setMaximumSize(new java.awt.Dimension(230, 480));
        backButton.setMinimumSize(new java.awt.Dimension(230, 480));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 80, 30));

        createProgressBar.setIndeterminate(true);
        getContentPane().add(createProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        creatingAccountLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        creatingAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        creatingAccountLabel.setText("Creating Account...");
        getContentPane().add(creatingAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, 30));

        createAccountBackground.setIcon(new javax.swing.ImageIcon("D:\\Java Projects\\myPad\\resources\\createImage.jpg")); // NOI18N
        getContentPane().add(createAccountBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 280, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCreateButtonActionPerformed
 
        String newUser = createUserField.getText();
        char[] passwordUserArray = createPasswordField.getPassword();
        String passwordUserString = "";
     
            for(int i = 0 ; i < passwordUserArray.length ; i++)
            {
                passwordUserString += passwordUserArray[i];
            }
       
        CreateAccountWorker cw = new CreateAccountWorker(newUser, passwordUserString, this){
        @Override
        protected void done(){
        
            createProgressBar.setVisible(false);
            creatingAccountLabel.setVisible(false);
        
        }
        
        };
        cw.execute();
        createProgressBar.setVisible(true);
        creatingAccountLabel.setVisible(true);
      
    }//GEN-LAST:event_createCreateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       int raspuns = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel?", "Warning!",  JOptionPane.YES_NO_OPTION);
       if(raspuns == JOptionPane.YES_OPTION){
           this.setVisible(false);
           new LogInFrame().setVisible(true);
       }
        
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel createAccountBackground;
    private javax.swing.JButton createCreateButton;
    private javax.swing.JPasswordField createPasswordField;
    private javax.swing.JProgressBar createProgressBar;
    private javax.swing.JTextField createUserField;
    private javax.swing.JLabel creatingAccountLabel;
    // End of variables declaration//GEN-END:variables
    
}
