/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notepad;

import com.ozten.font.JFontChooser;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class notepadd extends javax.swing.JFrame {

  Integer userIndexx = 0;
  
    public notepadd() {
        initComponents();
        customInit();
        
    }

    private void customInit() {
        this.currentSelectedTextArea = (AFCTextArea) this.tabbedPane.getSelectedComponent();
        this.currentSelectedTextArea.textArea.setDropTarget(new DropTarget() {
            @Override
            public void drop(DropTargetDropEvent dtde) {
                try {
                    dtde.acceptDrop(DnDConstants.ACTION_COPY_OR_MOVE);
                    List<File> list = (List<File>) dtde.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    list.forEach((file) -> {
                        createNewTab(file);
                    });

                } catch (UnsupportedFlavorException | IOException e) {
                }
            }
        });

        this.tabbedPane.addChangeListener(((e) -> {
            this.currentSelectedTextArea = (AFCTextArea) this.tabbedPane.getSelectedComponent();

            this.currentSelectedTextArea.textArea.setDropTarget(new DropTarget() {
                @Override
                public void drop(DropTargetDropEvent dtde) {
                    try {
                        dtde.acceptDrop(DnDConstants.ACTION_COPY_OR_MOVE);
                        List<File> list = (List<File>) dtde.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                        list.forEach((file) -> {
                            createNewTab(file);
                        });

                    } catch (UnsupportedFlavorException | IOException e) {
                    }
                }
            });
        }));

    }

    private void createNewTab(File file) {

        AFCTextArea textArea = new AFCTextArea();
        LoadWorker twerk = new LoadWorker(textArea.textArea, file);
        twerk.execute();
        textArea.path = file.toPath();
        this.tabbedPane.addTab(textArea.getFileName(), textArea);
        this.tabbedPane.setSelectedIndex(this.tabbedPane.getComponentCount() - 1);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        tabbedPane = new ClosableTabbedPane();
        aFCTextArea1 = new notepad.AFCTextArea();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        loggedinLabel = new javax.swing.JLabel();
        buttonOpen = new javax.swing.JButton();
        buttonSaveLocal = new javax.swing.JButton();
        buttonOpenFromCloud = new javax.swing.JButton();
        buttonSaveToCloud = new javax.swing.JButton();
        buttonSignOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        newTab = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuLoad = new javax.swing.JMenuItem();
        openFromDBmenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuSave = new javax.swing.JMenuItem();
        menuDBSave = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        signOutmenu = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuFont = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane.addTab("tab1", aFCTextArea1);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        loggedinLabel.setText("Logged in as:");

        buttonOpen.setIcon(new javax.swing.ImageIcon("D:\\Java Projects\\myPad\\resources\\openImage.png")); // NOI18N
        buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenActionPerformed(evt);
            }
        });

        buttonSaveLocal.setIcon(new javax.swing.ImageIcon("D:\\Java Projects\\myPad\\resources\\saveImage.png")); // NOI18N
        buttonSaveLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveLocalActionPerformed(evt);
            }
        });

        buttonOpenFromCloud.setIcon(new javax.swing.ImageIcon("D:\\Java Projects\\myPad\\resources\\openFromCloud.png")); // NOI18N
        buttonOpenFromCloud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenFromCloudActionPerformed(evt);
            }
        });

        buttonSaveToCloud.setIcon(new javax.swing.ImageIcon("D:\\Java Projects\\myPad\\resources\\saveOnCloud.png")); // NOI18N
        buttonSaveToCloud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveToCloudActionPerformed(evt);
            }
        });

        buttonSignOut.setIcon(new javax.swing.ImageIcon("D:\\Java Projects\\myPad\\resources\\signOutImage.png")); // NOI18N
        buttonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignOutActionPerformed(evt);
            }
        });

        menuFile.setText("File");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        newTab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newTab.setText("New Tab");
        newTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTabActionPerformed(evt);
            }
        });
        menuFile.add(newTab);
        menuFile.add(jSeparator1);

        menuLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuLoad.setText("Open");
        menuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoadActionPerformed(evt);
            }
        });
        menuFile.add(menuLoad);

        openFromDBmenu.setText("Open from database");
        openFromDBmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFromDBmenuActionPerformed(evt);
            }
        });
        menuFile.add(openFromDBmenu);
        menuFile.add(jSeparator3);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuSave);

        menuDBSave.setText("Save to database");
        menuDBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDBSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuDBSave);
        menuFile.add(jSeparator2);

        signOutmenu.setText("Sign out");
        signOutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutmenuActionPerformed(evt);
            }
        });
        menuFile.add(signOutmenu);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Edit");

        menuFont.setText("Font");
        menuFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFontActionPerformed(evt);
            }
        });
        menuEdit.add(menuFont);

        jMenuBar1.add(menuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchButton)
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(loggedinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSaveLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOpenFromCloud, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSaveToCloud, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSaveLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOpenFromCloud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSaveToCloud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loggedinLabel)))
        );

        buttonOpen.setToolTipText("Open an existing text file from local storage.");
        buttonSaveLocal.setToolTipText("Save text file on local storage.");
        buttonOpenFromCloud.setToolTipText("Open text file from cloud storage.");
        buttonSaveToCloud.setToolTipText("Save text file on cloud storage.");
        buttonSignOut.setToolTipText("Sign out from session.");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTabActionPerformed

        AFCTextArea textArea = new AFCTextArea();
        this.tabbedPane.addTab(" *untitled " + (this.tabbedPane.getComponentCount() + 1), textArea);

    }//GEN-LAST:event_newTabActionPerformed

    private void menuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoadActionPerformed

        fc.showOpenDialog(this);
        File file = this.fc.getSelectedFile();
        createNewTab(file);

    }//GEN-LAST:event_menuLoadActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed

        fc.showSaveDialog(this);
        this.saveFile(fc.getSelectedFile());


    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFontActionPerformed

        JFontChooser fontc = new JFontChooser();
        JOptionPane.showMessageDialog(null, fontc, "Alege Font", JOptionPane.PLAIN_MESSAGE);
        currentSelectedTextArea.textArea.setFont(fontc.getPreviewFont());
    }//GEN-LAST:event_menuFontActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed

    }//GEN-LAST:event_menuFileActionPerformed

    private void signOutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutmenuActionPerformed
        int raspuns = JOptionPane.showConfirmDialog(null, "Are you sure you want to sign out?", "Warning!", JOptionPane.YES_NO_OPTION);
        if (raspuns == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new LogInFrame().setVisible(true);
        }

    }//GEN-LAST:event_signOutmenuActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        HighlightWorker hw = new HighlightWorker(currentSelectedTextArea, searchTextField);
        hw.execute();


    }//GEN-LAST:event_searchButtonActionPerformed

    private void menuDBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDBSaveActionPerformed

        SaveToDBWorker stdb = new SaveToDBWorker(this.currentSelectedTextArea.textArea.getText(),this) {

            @Override
            public void done() {

                JOptionPane.showMessageDialog(null, "File saved. ", "Succes!", JOptionPane.INFORMATION_MESSAGE);
            }

        };
        stdb.execute();


    }//GEN-LAST:event_menuDBSaveActionPerformed

    private void openFromDBmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFromDBmenuActionPerformed

        OpenFromDBWorker o = new OpenFromDBWorker(this.currentSelectedTextArea.textArea,this);
        o.execute();

    }//GEN-LAST:event_openFromDBmenuActionPerformed

    private void buttonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenActionPerformed

        fc.showOpenDialog(this);
        File file = this.fc.getSelectedFile();
        createNewTab(file);

    }//GEN-LAST:event_buttonOpenActionPerformed

    private void buttonSaveLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveLocalActionPerformed
        fc.showSaveDialog(this);
        this.saveFile(fc.getSelectedFile());
    }//GEN-LAST:event_buttonSaveLocalActionPerformed

    private void buttonOpenFromCloudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenFromCloudActionPerformed

        OpenFromDBWorker o = new OpenFromDBWorker(this.currentSelectedTextArea.textArea,this) {

            @Override
            public void done() {

                JOptionPane.showMessageDialog(null, "File Opened. ", "Succes!", JOptionPane.INFORMATION_MESSAGE);

            }
        };

        o.execute();

    }//GEN-LAST:event_buttonOpenFromCloudActionPerformed

    private void buttonSaveToCloudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveToCloudActionPerformed

        SaveToDBWorker stdb = new SaveToDBWorker(this.currentSelectedTextArea.textArea.getText(),this) {

            @Override
            public void done() {

                JOptionPane.showMessageDialog(null, "File saved. ", "Succes!", JOptionPane.INFORMATION_MESSAGE);

            }

        };
        stdb.execute();

    }//GEN-LAST:event_buttonSaveToCloudActionPerformed

    private void buttonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignOutActionPerformed
        int raspuns = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Warning!", JOptionPane.YES_NO_OPTION);
        if (raspuns == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new LogInFrame().setVisible(true);
        }
    }//GEN-LAST:event_buttonSignOutActionPerformed

    private void saveFile(File file) {
        file = fc.getSelectedFile();
        String text2save = this.currentSelectedTextArea.textArea.getText();

        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            bw.write(text2save);
            bw.close();
        } catch (IOException e) {
        }
    }

    public static void main(String[] args) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notepadd().setVisible(true);

            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private notepad.AFCTextArea aFCTextArea1;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonOpenFromCloud;
    private javax.swing.JButton buttonSaveLocal;
    private javax.swing.JButton buttonSaveToCloud;
    private javax.swing.JButton buttonSignOut;
    private javax.swing.JFileChooser fc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel loggedinLabel;
    private javax.swing.JMenuItem menuDBSave;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFont;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem newTab;
    private javax.swing.JMenuItem openFromDBmenu;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JMenuItem signOutmenu;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
    private AFCTextArea currentSelectedTextArea;

    public void setLabel(String x) {

        this.loggedinLabel.setText(x);

    }
    public void setIndex(Integer index){
        
        this.userIndexx = index;
        
    }
    
    public Integer getIndex(){return this.userIndexx;}
}
